export const classes = [
  "Anthropology - ANTH",
  "Art - ART",
  "Art (Creative Studies) - ART CS",
  "Art History - ARTHI",
  "Art Studio - ARTST",
  "Asian American Studies - AS AM",
  "Astronomy - ASTRO",
  "Biology - BIOL",
  "Biology (Creative Studies) - BIOL CS",
  "Biomolecular Science and Engineering - BMSE",
  "Black Studies - BL ST",
  "Chemical Engineering CH E",
  "Chemistry (Creative Studies) - CHEM CS",
  "Chemistry - CHEM",
  "Chicano Studies - CH ST",
  "Chinese - CHIN",
  "Classics - CLASS",
  "Communication - COMM",
  "Comparative Literature - C LIT",
  "Computer Science - CMPSC",
  "Computer Science (Creative Studies) - CMPSCCS",
  "Computing (Creative Studies) - CMPTG",
  "Computing (Creative Studies) - CMPTGCS",
  "Counseling, Clinical, School Psychology - CNCSP",
  "Dance - DANCE",
  "Dynamical Neuroscience - DYNS",
  "Earth Science - EARTH",
  "East Asian Cultural Studies - EACS",
  "Ecology, Evolution & Marine Biology - EEMB",
  "Econommics - ECON",
  "Education - ED",
  "Electrical Computer Engineering - ECE",
  "Engineering Sciences - ENGR",
  "English - ENGL",
  "Environmental Data Science - EDS",
  "Environmental Science & Management - ESM",
  "Environmental Studies - ENV S",
  "Exercise & Sport Studies - ESS",
  "Exercise Sport - ES",
  "Feminist Studies - FEMST",
  "Film and Media Studies - FAMST",
  "French - FR",
  "General Studies - GEN S",
  "General Studies (Creative Studies) - GEN SCS",
  "Geography - GEOG",
  "German - GER",
  "Global Peace and Security - GPS",
  "Global Studies - GLOBL",
  "Graduate Division - GRAD",
  "Greek - GREEK",
  "Hebrew - HEB",
  "History - HIST",
  "Interdisciplinary - INT",
  "Interdisciplinary (Creative Studies) - INT CS",
  "Italian - ITAL",
  "Japanese - JAPAN",
  "Korean - KOR",
  "Latin - LATIN",
  "Latin American and Iberian Studies - LAIS",
  "Linguistics - LING",
  "Literature - LIT",
  "Literature (Creative Studies) - LIT CS",
  "Marine Science - MARSC",
  "Materials - MATRL",
  "Mathematics - MATH",
  "Mathematics (Creative Studies) - MATH CS",
  "Mechanical Engineering - ME",
  "Media Arts and Technology - MAT",
  "Medieval Studies - ME ST",
  "Middle East Studies - MES",
  "Military Science - MS",
  "Molecular, Cellular & Developmental Biology - MCDB",
  "Music - MUS",
  "Music (Creative Studies) - MUS CS",
  "Music Performance Laboratories - MUS A",
  "Philosophy - PHIL",
  "Physics - PHYS",
  "Physics (Creative Studies) - PHYS CS",
  "Political Science - POL S",
  "Portuguese - PORT",
  "Psychology - PSY",
  "Religious Studies - RG ST",
  "Renaissance Studies - RENST",
  "Russian - RUSS",
  "Slavic - SLAV",
  "Sociology - SOC",
  "Spanish - SPAN",
  "Speech & Hearing Science - SHS",
  "Statistics & Applied Probability - PSTAT",
  "Technology Management - TMP",
  "Theater - THTR",
  "Writing - WRIT",
  "Writing & Literature - W&L",
  "Writing & Literature (Creative Studies) - W&L CS",
];
